# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: scrcpy

# ==================== Daily ====================

DailyQuest:
  Scheduler:
    Enable: true
BattlePass:
  Scheduler:
    Enable: true
Assignment:
  Scheduler:
    Enable: true
Freebies:
  Scheduler:
    Enable: true
MissionReward:
  Scheduler:
    Enable: true
Mail:
  Scheduler:
    Enable: true
Knights:
  Scheduler:
    Enable: true
PetsGift:
  Scheduler:
    Enable: true

# ==================== Weekly ====================

Weekly:
  DungeonSupport:
    Use: do_not_use
