# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: scrcpy

# ==================== Daily ====================

MissionReward:
  Scheduler:
    Enable: true
Mail:
  Scheduler:
    Enable: true
DataUpdate:
  Scheduler:
    Enable: true
SanctuaryDaily:
  Scheduler:
    Enable: true
Knights:
  Scheduler:
    Enable: true
Arena:
  Scheduler:
    Enable: true
PetsGift:
  Scheduler:
    Enable: true
SecretShop:
  Scheduler:
    Enable: true
Gacha:
  Scheduler:
    Enable: true
