# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    MissionReward:
      - Scheduler
      - MissionReward
    Mail:
      - Scheduler
      - Mail
    DataUpdate:
      - Scheduler
      - Dashboard
    SanctuaryDaily:
      - Scheduler
    Knights:
      - Scheduler
      - Knights
      - KnightsTeamBattle
    Arena:
      - Scheduler
      - Arena
    Store:
      - Scheduler
      - StoreDaily
      - StoreWeekly
    PetsGift:
      - Scheduler
      - PetsGift
    SecretShop:
      - Scheduler
      - SecretShop
    Combat:
      - Scheduler
      - Combat
      - CombatRuntime
    Gacha:
      - Scheduler
      - Gacha
    Pets:
      - Scheduler

# ==================== Monthly ====================

Monthly:
  menu: 'list'
  page: 'setting'
  tasks:
    SanctuaryMonthly:
      - Scheduler
      - SanctuaryMonthly
