import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '02:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android, cloud_android
    Emulator_PackageName = 'auto'  # auto, CN-Official, OVERSEA-Play
    Emulator_GameLanguage = 'cn'  # auto, cn, en
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game, close_emulator

    # Group `MissionReward`
    MissionReward_ClaimDailyRewards = True

    # Group `Mail`
    Mail_CollectWithin = '1d'  # 1h, 1d
    Mail_LastCheckAt = datetime.datetime(2020, 1, 1, 0, 0)
    Mail_LastRemainingText = None
    Mail_LastRemainingSince = datetime.datetime(2020, 1, 1, 0, 0)

    # Group `CommunityAio`
    CommunityAio_CredentialsFile = None

    # Group `CommunityAuth`
    CommunityAuth_CredentialsFile = None
    CommunityAuth_WaitTimeout = 300  # 60, 180, 300, 600

    # Group `Knights`
    Knights_ClaimSigninRateReward = True
    Knights_Support = True
    Knights_SupportLowerLevelFairyFlower = True
    Knights_SupportBeginnerPenguin = True
    Knights_RequestItem = 'LowerLevelFairyFlower'  # LowerLevelFairyFlower, BeginnerPenguin
    Knights_WeeklyTask = True
    Knights_WorldBoss = True

    # Group `KnightsTeamBattle`
    KnightsTeamBattle_TeamBattle = True
    KnightsTeamBattle_Reminder = False
    KnightsTeamBattle_ReminderLeadMinutes = 60  # 30, 60, 120, 180
    KnightsTeamBattle_ReminderLastEnd = None

    # Group `Arena`
    Arena_ClaimWeeklyRewards = True
    Arena_ClaimWeeklyBattleRewards = True
    Arena_ClaimBattlePassRewards = True
    Arena_NPCCombat = True
    Arena_NPCCombatFastBattle = True
    Arena_NPCCombatCount = 5

    # Group `StoreDaily`
    StoreDaily_BuyDailyFreeItem = True
    StoreDaily_BuyFriendshipMobility40 = True
    StoreDaily_BuyFriendshipArenaFlag = True
    StoreDaily_BuyConquestMobility40 = 0  # 0, 1, 2, 3

    # Group `StoreWeekly`
    StoreWeekly_BuyConquestMorogora = False
    StoreWeekly_BuyFriendshipArtifactEnhancementStone = 0  # 0, 1, 2, 3
    StoreWeekly_BuyInheritanceMorogora = 0  # 0, 1, 2
    StoreWeekly_BuyInheritancePotentialFragments = 0  # 0, 1, 2

    # Group `PetsGift`
    PetsGift_LastClaimAt = datetime.datetime(2020, 1, 1, 0, 0)

    # Group `Combat`
    Combat_Mode = 'Task'  # Task, Event
    Combat_Domain = 'Hunt'  # Hunt, SpiritAltar
    Combat_Element = 'Water'  # Dark, Light, Water, Fire, Nature
    Combat_AltarGrade = 'Hell'  # Pri, Mid, High, Hell
    Combat_HuntGrade = 'Hell'  # Mid, High, Hell, Dimensional
    Combat_FastCombat = True
    Combat_FastCombatCount = 10
    Combat_RepeatCombatCount = 5

    # Group `CombatRuntime`
    CombatRuntime_Session = {}

    # Group `SecretShop`
    SecretShop_OnlyFree = True
    SecretShop_MaxRefresh = 10
    SecretShop_BuyCovenantBookmark = True
    SecretShop_BuyMysticMedal = True

    # Group `Gacha`
    Gacha_CollectGoldenInheritance = True

    # Group `Dashboard`
    Dashboard_Gold = {}
    Dashboard_Skystone = {}
    Dashboard_Stamina = {}
    Dashboard_EquipmentInventory = {}
    Dashboard_DailyActivity = {}
    Dashboard_ArenaRank = {}
    Dashboard_ArenaFlag = {}
    Dashboard_ConquestPoint = {}
    Dashboard_ShadowCommission = {}
    Dashboard_TeamBattle = {}

    # Group `SanctuaryMonthly`
    SanctuaryMonthly_RewardTier = 'A'  # A, B, S, MaxMinus1, MaxMinus2
